### ISSUE TITLE
Getting `container isn't ready: Unknown` error

### ISSUE THREAD

**Issue by 1pav** [MihaiBalint/dfsync#23]
When trying to dfsync a container that for some reason has crashed (e.g. previously synced changes contained some bug), I get this error:

```
<path-to-file> will not sync in <container-name>, container isn't ready: Unknown
```

As a result, I can't sync files any more (unless I press Ctrl-C or X and let dfsync restore the original container).

Note: This issue was created prior to the release of 0.4.6.

**Comment by MihaiBalint** [comment]
The latest dfsync version will now replace container startup and readiness probes such that syncing bad/broken code will no longer cause the container to enter crash-loops, your containerised process will still be crashing but it can recover if working code is synced.

I'm closing this now, please reopen if it's still not working for you.

Thanks for the report.
